# 心理统计枕边书 {.unnumbered}

## English Version

Use the button in the top-right corner to access the English version or simply click [here](https://linwz-psychstats.share.connect.posit.cloud/en/index.html).

Currently, the English version is AI-translated with no thorough proofreading. I will rewrite the English version after the Chinese version is complete.

## 本书网址迁移

因为bookdown.org 服务终止(see https://posit.co/blog/bookdown-org-sunset/), 本书地址将迁移至posit connect cloud,地址是 https://linwz-psychstats.share.connect.posit.cloud/ 。

## 序

开始写本书的直接原因是想要在中文互联网上留下我个人主页（ <https://www.linwz.com> ）的痕迹。因为今年想更新我工作单位网站上的个人介绍时，由于越收越紧的审核，把我的个人网站的网址删去了。而我的个人网站提交给国内的搜索引擎已经两三年了，始终没有收录和索引。这样就直接导致中文互联网完全无法通过搜索引擎找到我的网站，我的招生要求和信息以及一些个人美好的品质就要消失于中文互联网了。这时，我的同事顺便也是好友李喻骏给我提供了一个新的思路。他之前上课之余撰写的巨著 [Welcome \| R 语言：从基础到进阶](https://bookdown.org/pheebie2008/RBA/) 能在中文搜索引擎上检索到。于是，为了给未来希望找到我个人网站从而了解我作为导师的个人信息的本科与研究生提供一个窗口，我决定也整一本书。是的，我是为*你们*写的这本书，请一定要读完（凝视.gif）。

所以接下来的问题就变成了写什么。我是一个主要方向为人格与社会心理学的一事无成的心理学工作者，为了指导专业硕士（以及结合社会问题）也杂七杂八地做一些管理心理学与消费决策心理学的东西。但是以上这些领域我是一个字都憋不出来的。作为这个领域的研究者，我深感自己的能力和积累不足，完全没有信口胡诌的勇气。但是，由于我自己也不务正业地上着一门跟统计有关的方法课程，在李喻骏博士的启发下，虽然我在自己的研究领域里唯唯诺诺，但完全可以去非专业领域重拳出击啊（笑）。所以，本书的主题实为统计。

如果说，这本所谓的统计书相比那些专业人士撰写的统计教材真的有什么优势的话，那么我认为这一定就是我的不专业。众所周知，学习任何东西，向那个领域里的天才学习是不明智的。他们只会告诉你，没什么难的，看一看就学会了。是的，我的优势在于，我（应该更）懂读者的困惑，我可以以一种局外人的视角跟读者一起从头理解心理统计（或者所有相关领域使用类似方法的学科统计）。

简而言之，这本书并不是一本统计的教科书，它撑死了是一本教辅。而我对它的定位是一本科普读物，正如它的名字一样，我希望它是一本你在闲暇时间，在睡前能拿起来看一看，能在过程中感到一丝趣味性的读本。当然，你也可以理解为这是一本催眠书，毕竟谁学统计的时候不困呢？霍金在《时间简史》里说，有人告诉他“每个数学公式都可能让书的销量减少一半”。不过我这本书目前没有什么销售的指望，所以我会在各种机会卖弄我对公式和方程的错误理解。是的，这是一本定位为科普读物但是塞满数学符号的书，而且这样还不保证任何专业性。本书在任何情况下都不适合作为一本工具书使用。如果你需要一本专业的、深入的、准确的统计教材，我向你推荐李喻骏博士的鸿篇巨制 [Linear Model](https://bookdown.org/Yujun_Li_QuantPsych/linear_model/)。希望我们这两本书能够在一定程度上互相补充。不过，我是不会迁就他的内容写书的。另外一个推荐是 Andy Field 的 Discovering Statistics 系列，作为本科阶段的基础统计教材，我认为基本无出其右。有SPSS的版本和R的版本，缺点是目前好像只有英文版本，而且通过官方渠道购买非常贵（以中国的物价）。

本书使用R作为统计工具，各种统计检验基本都使用代码完成。我会在书的开始尽量详细地注释代码的每一步帮助你理解在做什么。你也可以选择无视代码，直接查看代码输出的结果。如果你需要详尽的对于R代码的学习手册，可以查看上面提到的李喻骏博士在中文搜索引擎排名前列[^index-1]的名著。有一点需要克服的是r代码输出的结果均为英文，目前我没有找到（也不打算找）解决方法。如果真的对英文有原始的畏惧，你可以使用AI转换成中文查看。而在正文中引述统计结果时，我会直接复制粘贴，而不是使用 APA 格式，这一点请务必海涵。

[^index-1]: 搜索词是他自己的名字。显然。

在内容上，本书的定位是中级统计知识。换句话说，尽管我会尽量介绍一些前置知识，但我心中预设的读者是心理学或相关专业的同学，在学完心理统计，一定程度上理解基础的统计知识（知道方差分析与回归分析大致是什么）。你可以把它作为本科阶段学习心理统计时的补充读物，或者在学习“高级”统计前补充的前置知识。

我想感谢在学习统计的路上指引我的几位老师，刘红云教授，Dr. Tsai, Fenfang, Dr. Cheung, Mike （按我上几位老师课的时间顺序排序）。好在几位老师都没有预见到我未来的胆大包天，竟敢开始写起统计有关的书来，所以没像菩提祖师交待悟空那样嘱咐：“你这去，定生不良。凭你怎么惹祸行凶，却不许说是我的徒弟。你说出半个字来，我就知之，把你这猢狲剥皮锉骨，将神魂贬在九幽之处，教你万劫不得翻身！”所以在他们（万一）看到这本书之前，我还能列一列他们的名字表达感激。尽管写到这里时，全书正文一个字都没写下，但这本书中有那么些价值的知识、逻辑甚至思想，都不可避免地直接来源于他们对我——一名并不出众的普通学生——的统计训练。而这本书中的错漏，要归罪于我没有好好听讲，自身能力与认识不够。如果不小心真的成书，里面的错漏就要完全怪罪本书的审订者李喻骏博士，他已经答应我会帮助审阅纠正书中的错误。敬请读者对他怀有一颗包容的心，在发现问题后不吝发邮件给我纠正，此致敬礼。

最后，再次强调一下我的个人主页是 <https://www.linwz.com> 。上面其实只有我们课题组相关的招生信息和资源。不过如果万幸我能完成这本书的话，我会把英文版本以及全书的 pdf 与 epub 版本放在上面，以期增加一些流量。

本书使用的开源协议为 [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1) 。书中除R代码生成的图表外的插图，如无额外标注，均使用 ChatGPT 网页版生成，根据其协议，生成图内容版权归属用户，因此这些生成的图片也遵守上述开源协议。

::: callout-important
目前本书仍在施工中，大部分章节未完成，请见谅。

因为发现自己有时候会返回去修改之前的章节，所以还是记录一下修改历史，方便自己和读者。开始记录时间为20251014,目前四章版本。

<!-- AUTO-CHANGELOG-START -->
20251014: 在第四章中，增加“思考：一个没想好题目的关于事前事后比较的讨论”。

20251015: 在第四章中，增加介绍对比编码中，使用分数的编码选择。

20251018：在第四章中增加介绍不平衡样本的编码方法；修订第四章的数据框与模型编号系统。

20260929: 增加了由ai翻译的[英语版本](https://linwz-psychstats.share.connect.posit.cloud/en/index.html)，可以由右上角按钮进入。在第四章增加了对编码变量个数为k-1的示例解释。并没有偷懒（好吧有一点点），其实一直在写第五章，越写越多导致难产。
<!-- AUTO-CHANGELOG-END -->
:::
